server:
  port: 8000
spring:
  profiles:
    active: true
  #数据源配置
  datasource:
    username: root
    password: Root123456**
    url: jdbc:mysql://localhost:3306/project_final?useUnicode=true
    driver-class-name: com.mysql.cj.jdbc.Driver
  redis:
    host: localhost
    port: 6379
    password: wuyutao
  mail:
    host: smtp.qq.com
    username: 245149633@qq.com
    password: dvvgdpcjulrfbhba
    properties:
      mail.smtp.ssl.enable: true
  application:
    name: auth-service
mybatis:
  mapper-locations: classpath:/auth/dao/mapper/*.xml
  type-aliases-package: auth.entity
eureka:
  client:
    service-url:
      defaultZone: http://localhost:7001/eureka/
myconfig:
  web-url: https://wytcloud.top
