server:
  port: 8000
spring:
  #数据源配置
  datasource:
    username: root
    password: root
    url: jdbc:mysql://localhost:3306/personal_project?useUnicode=true
    driver-class-name: com.mysql.cj.jdbc.Driver
  redis:
    host: localhost
    port: 6379
    password: wuyutao
  mail:
    host: smtp.office365.com
    username: NonTalkPeach@hotmail.com
    password: tbc7gvlgej7wy3oo
    properties:
      mail.smtp.auth: true
      mail.smtp.starttls.enable: true
      mail.smtp.starttls.required: true
  application:
    name: auth-service
mybatis:
  mapper-locations: classpath:/auth/dao/mapper/*.xml
  type-aliases-package: auth.entity
eureka:
  client:
    service-url:
      defaultZone: http://localhost:7001/eureka/
myconfig:
  web-url: http://wytcloud.top
