server:
  port: 8002
spring:
  profiles:
    active: true
  #数据源配置
  datasource:
    username: root
    password: Root123456**
    url: jdbc:mysql://120.78.164.88:3306/project_final?useUnicode=true
    driver-class-name: com.mysql.cj.jdbc.Driver
  application:
    name: blog-service
mybatis:
  mapper-locations: classpath:/blog/dao/mapper/*.xml
  type-aliases-package: blog.entity
eureka:
  client:
    service-url:
      defaultZone: http://localhost:7001/eureka/
  instance:
    ip-address: 39.102.40.67
    prefer-ip-address: true
