# 该微服务对外网开放
# 开放部分接口
# 开放静态资源访问

server:
  port: 8001
spring:
  #数据源配置
  datasource:
    username: root
    password: root
    url: jdbc:mysql://localhost:3306/project_final?useUnicode=true
    driver-class-name: com.mysql.cj.jdbc.Driver
  web:
    resources:
      static-locations:
        - classpath:/public
        - file:${myconfig.public-file-location}
  application:
    name: file-service
mybatis:
  mapper-locations: classpath:/file/dao/mapper/*.xml
  type-aliases-package: file.entity
eureka:
  client:
    service-url:
      defaultZone: http://localhost:7001/eureka/
myconfig:
  public-file-location: /home/wuyutao/project_final/file_statis
  file-location: /home/wuyutao/project_final/file_upload