server:
  port: 8787
spring:
  thymeleaf:
    cache: false
  redis:
    host: localhost
    port: 6379
    password: wuyutao
eureka:
  client:
    register-with-eureka: false #是否向注册中心注册自己 消费者不需要注册自己
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:7001/eureka/
myconfig:
  file-server-url: http://wytcloud.top:8001
